# Generated by Django 3.0.5 on 2020-04-30 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('genre', models.CharField(max_length=50)),
                ('pages', models.IntegerField(default=0)),
                ('description', models.TextField()),
                ('image', models.ImageField(default='default_book.jpg', upload_to='book_pic')),
                ('source', models.URLField(max_length=300)),
            ],
        ),
    ]
