# Generated by Django 3.0.5 on 2020-04-30 03:18

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('book_library', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='book',
            name='published_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 30, 3, 18, 21, 244630, tzinfo=utc)),
        ),
    ]
