# Generated by Django 3.0.5 on 2020-04-30 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_library', '0003_auto_20200430_0318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='source',
            field=models.URLField(max_length=250),
        ),
    ]
