# Generated by Django 3.0.5 on 2020-04-28 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20200428_2029'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='profile_pic',
            field=models.ImageField(default='default.png', upload_to=''),
        ),
        migrations.AlterField(
            model_name='comment',
            name='author',
            field=models.CharField(default='', max_length=100),
        ),
    ]
